---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd1
  namespace: demo1
  annotations:
    volume.alpha.kubernetes.io/storage-class: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd2
  namespace: demo1
  annotations:
    volume.alpha.kubernetes.io/storage-class: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd3
  namespace: demo1
  annotations:
    volume.alpha.kubernetes.io/storage-class: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
